/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.au.cc.gallery;

import  edu.au.cc.gallery.tools.*;

public class App {
    public String getGreeting() {
        return "Hello Kenneth.";
    }

    public static void main(String[] args) throws Exception {
        //System.out.println(new App().getGreeting());
	//s3.demo();
        // DB.demo();
        UserAdmin admin = new UserAdmin();
        admin.userMenu();
    }
}
