/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.au.cc.gallery;

public class App {
    public String getGreeting() {
        return "Hello Kenneth.";
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
	s3.demo();
    }
}
